### ISSUE TITLE
State Highlighting Issue

### ISSUE THREAD

**Issue by JonathanRider** [deleidos/prototype-20150626#1]
Sometimes, when mousing over the map, after a state is highlighted, it does not un-highlight.

To reproduce this bug:

Reload the page and go to Search by manufacturer and search for a random one (I typed in “a” and clicked on Pharmacia and Upjohn Company).
Switch to Search by Drug and search for a random one (Typed in “a” and chose CLEOCIN PHOSPHATE)
Then, move your cursor around the map. After a state is highlighted, it doesn’t un-highlight, so it looks like you’re drawing on the map.

This was done in chrome

**Comment by td-edge** [comment]
Even though the leaflet-directive for angular has a built in option called "resetStyleOnMouseout," the user can confuse the event handler by having the mouse hovering on a geoJSON area before it is fully loaded. In order to combat this effect, we added a custom listener for the mouseout action:

``` javascript
        $scope.$on("leafletDirectiveGeoJson.mouseout", function(event, args){
            if (tab != "maker") {
                var layer = args.leafletEvent.target
                layer.setStyle({
                    fillColor: 'orange'
                })
            }
        });
```
